### ISSUE TITLE
An outdated yeoman-generator dependency raises CSS warnings and version errors

### ISSUE THREAD

**Issue by magp** [yeoman/generator-bootstrap#40]
Hi,

Thanks for the workflow. Unfortunately, I am getting the errors detailed below when executing:
```
npm install -g generator-bootstrap
```
Errors:
```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
...
UNMET PEER DEPENDENCY yo@>=1.0.0
npm WARN EPEERINVALID generator-bootstrap@0.2.1 requires a peer of yo@>=1.0.0 but none was installed.
```

For other generators this has been fixed by simply updating the yeoman-generator dependency to the newer version. Nevertheless, I may be very wrong.

Thanks again for the work on this generator and on yeoman.

**Comment by kikeonline** [comment]
`UNMET PEER DEPENDENCY yo@>=1.0.0`

`npm WARN EPEERINVALID generator-bootstrap@0.2.1 requires a peer of yo@>=1.0.0 but none was installed.`

**Comment by magp** [comment]
@kikeonline you can avoid that error by reinstalling yo in the same command:
```
npm -g install yo generator-bootstrap
```
This happens with many generators. Not sure what has gone wrong as no one seems to have a proper solution. I've seen repos simply remove the yo dependancy and call it fixed. I'm a noob so I might be missing something.

Anyway, alluding to the above I believe we can separate the problem into two parts.

The first takes into account the errors for the outdated dependancy, that can be easily solved by updating it.

The second relates to the yo dependancy. Not sure how to fix this one except for the hack explained above. It is a generalised problem that can be avoided in all cases I have encountered with the yo reinstall.

Sorry I can't enlighten further. I am happy to do testing for you guys but can do little else as my knowledge is limited.

**Comment by SBoudrias** [comment]
> I've seen repos simply remove the yo dependancy and call it fixed. I'm a noob so I might be missing something.

That's the correct fix. npm removed support `peerDependencies` anymore and that's why you see these warnings.

**Comment by SBoudrias** [comment]
Fixed.

**Comment by magp** [comment]
@SBoudrias Thanks for the information. Good to understand what is going on.
